Repository SUI-Components/sui, pull requests merged in 2020-06, with the labels that each got.

#842 Perf/use typescript interfaces instead javascript
  packages/sui-domain/src/NotImplementedUseCase.js
  packages/sui-domain/src/fetcher/AxiosFetcher.js
  packages/sui-domain/src/fetcher/Fetcher.js
  packages/sui-domain/src/fetcher/FetcherInterface.d.ts
Labels: not-ready

#834 [Feature] @s-ui/studio run tests in the cli
  packages/sui-studio/README.md
  packages/sui-studio/bin/sui-studio-test.js
  packages/sui-studio/bin/sui-studio.js
  packages/sui-studio/package.json
  packages/sui-studio/src/components/tryRequire.js
  packages/sui-studio/src/patcher-mocha/index.js
  packages/sui-studio/src/runtime-mocha/index.js
  packages/sui-test/bin/karma/babelPatch.js
  packages/sui-test/bin/karma/config.js
  packages/sui-test/bin/karma/index.js
  packages/sui-test/package.json
Labels: feature, to review

#872 [sui-bundler] create a new Request for each entry in the manifest
  packages/sui-bundler/service-worker.js
Labels: bug
