Repository SUI-Components/sui, pull requests merged in 2022-10, with the labels that each got.

#1473 Chore/update axios
  packages/sui-domain/package.json
  packages/sui-mockmock/package.json
Labels: hacktoberfest-accepted

#1474 Chore/update node fetch
  packages/sui-ci/package.json
  packages/sui-critical-css/package.json
  packages/sui-studio/package.json
Labels: hacktoberfest-accepted

#1475 feat(packages/sui-precommit): update dset to latest version
  packages/sui-precommit/bin/sui-precommit.js
  packages/sui-precommit/package.json
Labels: hacktoberfest-accepted

#1476 feat(packages/sui-decorators): update redis-mock and redis dependencies
  packages/sui-decorators/package.json
Labels: hacktoberfest-accepted

#1481 feat(packages/sui-mono): add "refactor" as commit type with release
  packages/sui-mono/src/check.js
  packages/sui-mono/test/server/checkSpec.js
Labels: feature, hacktoberfest-accepted, hacktoberfest

#1491 refactor(packages/sui-studio): Improve navigation of the header
  packages/sui-studio/src/components/demo/_style.scss
  packages/sui-studio/src/components/layout/Logo.js
  packages/sui-studio/src/components/layout/_style.scss
  packages/sui-studio/src/components/layout/index.js
  packages/sui-studio/src/components/navigation/_style.scss
  packages/sui-studio/src/components/navigation/index.js
  packages/sui-studio/src/components/workbench/_style.scss
  packages/sui-studio/src/styles/_settings.scss
Labels: docs, hacktoberfest-accepted, hacktoberfest, enhacement

#1483 feat(packages/sui-studio): Delete excess code for ux tab
  packages/sui-studio/bin/helpers/copyStaticFiles.js
  packages/sui-studio/src/components/workbench/index.js
  packages/sui-studio/src/constants.js
  packages/sui-studio/src/routes.js
Labels: not-ready, hacktoberfest-accepted, hacktoberfest

#1494 docs(packages/sui-studio): Improve and standardise hierarchy of texts
  packages/sui-studio/src/components/documentation/markdown.css
  packages/sui-studio/src/components/layout/_style.scss
  packages/sui-studio/src/components/navigation/_style.scss
  packages/sui-studio/src/components/workbench/_style.scss
  packages/sui-studio/src/styles/_default.scss
Labels: docs, hacktoberfest-accepted, enhacement

#1498 feat(packages/sui-studio): Remove title of the Themes tabs
  packages/sui-studio/src/components/demo/Tabs.js
Labels: docs, hacktoberfest-accepted, hacktoberfest, enhacement

#1497 feat(packages/sui-domain): allow inject logger from outside
  packages/sui-domain/README.md
  packages/sui-domain/src/EntryPointFactory.js
  packages/sui-domain/test/common/EntryPointSpec.js
  packages/sui-domain/test/common/fixtures/EmptyUseCaseWithLogger.js
  packages/sui-domain/test/common/fixtures/factoryWithMultipleUseCasesAndLogger.js
  packages/sui-domain/test/common/fixtures/factoryWithSingleUseCaseAndLogger.js
Labels: hacktoberfest-accepted, hacktoberfest

#1507 fix(packages/sui-studio): Add a fill to the buttons icon
  packages/sui-studio/src/components/icons/index.js
  packages/sui-studio/src/components/layout/_style.scss
Labels: bug, hacktoberfest-accepted, hacktoberfest

#1499 refactor(packages/sui-studio): remove not used scss
  packages/sui-studio/src/styles/components/_tabs.scss
Labels: hacktoberfest-accepted

#1509 fix(packages/sui-studio): hide menu clicking on an overlay in mobile
  packages/sui-studio/src/components/layout/_style.scss
  packages/sui-studio/src/components/layout/index.js
Labels: hacktoberfest-accepted, enhacement

#1506 update bottom padding in NavBar menu to 80px and reduce the sidebar height by 48px
  packages/sui-studio/src/components/layout/_style.scss
  packages/sui-studio/src/components/navigation/_style.scss
Labels: docs, hacktoberfest-accepted, enhacement
