Repository SUI-Components/sui, pull requests merged in 2025-01, with the labels that each got.

#1888 feat(packages/sui-dashboard): compatible with node 20 require fn way
  packages/sui-dashboard/package.json
  packages/sui-dashboard/src/index.js
Labels: a11y

#1890 feat(packages/sui-lint): match all adv orgs
  packages/sui-lint/eslintrc.js
  packages/sui-lint/eslintrc.ts.js
Labels: feature, a11y

#1895 fix(packages/sui-studio): wrong color name token
  package-lock.json
  packages/sui-studio/src/styles/_settings.scss
Labels: a11y

#1896 fix(packages/sui-studio): remove unnecesary sui-studio dependency
  package-lock.json
  packages/sui-studio/package.json
  packages/sui-studio/src/components/switch/_style.scss
  packages/sui-studio/src/components/switch/index.js
  packages/sui-studio/src/index.scss
Labels: bug, a11y

#1894 feat(packages/sui-segment-wrapper): get client id synchronously
  packages/sui-segment-wrapper/src/segmentWrapper.js
Labels: feature

#1898 feat(packages/sui-segment-wrapper): send adobe mvcid along the ga event
  packages/sui-segment-wrapper/src/index.js
  packages/sui-segment-wrapper/src/segmentWrapper.js
Labels: feature
